from django.conf.urls import url, include
from . import views
from .views import ProfileCreateView, IndexView, DetailView, result_minority_north_east



app_name = 'polls'

urlpatterns = [
	url(r'^create_profile/$', ProfileCreateView.as_view(), name='create_profile'),
	url(r'^(?P<pk>\d+)/$', DetailView.as_view(), name='detail'),
	#url(r'^(?P<pk>\d+)/result/$', ResultView.as_view(), name='result'),
	url(r'^(?P<poll_id>\d+)/result_all/$', views.result_all, name='result_all'),
	url(r'^(?P<poll_id>\d+)/result_male/$', views.result_male, name='result_male'),
	url(r'^(?P<poll_id>\d+)/result_female/$', views.result_female, name='result_female'),
	url(r'^(?P<poll_id>\d+)/result_age_18_24/$', views.result_age_18_24, name='result_age_18_24'),
	url(r'^(?P<poll_id>\d+)/result_age_25_34/$', views.result_age_25_34, name='result_age_25_34'),
	url(r'^(?P<poll_id>\d+)/result_age_35_44/$', views.result_age_35_44, name='result_age_35_44'),
	url(r'^(?P<poll_id>\d+)/result_age_45_54/$', views.result_age_45_54, name='result_age_45_54'),
	url(r'^(?P<poll_id>\d+)/result_age_55_64/$', views.result_age_55_64, name='result_age_55_64'),
	url(r'^(?P<poll_id>\d+)/result_age_65_/$', views.result_age_65_, name='result_age_65_'),
	url(r'^(?P<poll_id>\d+)/result_hausa_fulani/$', views.result_hausa_fulani, name='result_hausa_fulani'),
	url(r'^(?P<poll_id>\d+)/result_igbo/$', views.result_igbo, name='result_igbo'),
	url(r'^(?P<poll_id>\d+)/result_yoruba/$', views.result_yoruba, name='result_yoruba'),
	url(r'^(?P<poll_id>\d+)/result_minority_south_south/$', views.result_minority_south_south, name='result_minority_south_south'),
	url(r'^(?P<poll_id>\d+)/result_minority_north_central/$', views.result_minority_north_central, name='result_minority_north_central'),
	url(r'^(?P<poll_id>\d+)/result_minority_north_east/$', views.result_minority_north_east, name='result_minority_north_east'),
	url(r'^(?P<poll_id>\d+)/result_north_west/$', views.result_north_west, name='result_north_west'),
	url(r'^(?P<poll_id>\d+)/result_north_east/$', views.result_north_east, name='result_north_east'),
	url(r'^(?P<poll_id>\d+)/result_north_central/$', views.result_north_central, name='result_north_central'),
	url(r'^(?P<poll_id>\d+)/result_south_west/$', views.result_south_west, name='result_south_west'),
	url(r'^(?P<poll_id>\d+)/result_south_east/$', views.result_south_east, name='result_south_east'),
	url(r'^(?P<poll_id>\d+)/result_south_south/$', views.result_south_south, name='result_south_south'),
	url(r'^(?P<poll_id>\d+)/result_diaspora/$', views.result_diaspora, name='result_diaspora'),
	url(r'^(?P<poll_id>\d+)/result_less_secondary/$', views.result_less_secondary, name='result_less_secondary'),
	url(r'^(?P<poll_id>\d+)/result_secondary/$', views.result_secondary, name='result_secondary'),
	url(r'^(?P<poll_id>\d+)/result_graduate/$', views.result_graduate, name='result_graduate'),
	url(r'^(?P<poll_id>\d+)/result_postgraduate/$', views.result_postgraduate, name='result_postgraduate'),
	url(r'^(?P<poll_id>\d+)/result_currently_unemployed/$', views.result_currently_unemployed, name='result_currently_unemployed'),
	url(r'^(?P<poll_id>\d+)/result_employed_full_time/$', views.result_employed_full_time, name='result_employed_full_time'),
	url(r'^(?P<poll_id>\d+)/result_employed_part_time/$', views.result_employed_part_time, name='result_employed_part_time'),
	url(r'^(?P<poll_id>\d+)/result_self_employed/$', views.result_self_employed, name='result_self_employed'),
	url(r'^(?P<poll_id>\d+)/result_student/$', views.result_student, name='result_student'),
	url(r'^(?P<poll_id>\d+)/result_retired/$', views.result_retired, name='result_retired'),
	url(r'^(?P<poll_id>\d+)/result_less_18000/$', views.result_less_18000, name='result_less_18000'),
	url(r'^(?P<poll_id>\d+)/result_18000_50000/$', views.result_18000_50000, name='result_18000_50000'),
	url(r'^(?P<poll_id>\d+)/result_51000_100000/$', views.result_51000_100000, name='result_51000_100000'),
	url(r'^(?P<poll_id>\d+)/result_101000_200000/$', views.result_101000_200000, name='result_101000_200000'),
	url(r'^(?P<poll_id>\d+)/result_201000_500000/$', views.result_201000_500000, name='result_201000_500000'),
	url(r'^(?P<poll_id>\d+)/result_500000/$', views.result_500000, name='result_500000'),
	url(r'^(?P<poll_id>\d+)/result_single_never_married/$', views.result_single_never_married, name='result_single_never_married'),
	url(r'^(?P<poll_id>\d+)/result_divorced_separated/$', views.result_divorced_separated, name='result_divorced_separated'),
	url(r'^(?P<poll_id>\d+)/result_married/$', views.result_married, name='result_married'),
	url(r'^(?P<poll_id>\d+)/result_widowed/$', views.result_widowed, name='result_widowed'),
	url(r'^(?P<poll_id>\d+)/result_christianity/$', views.result_christianity, name='result_christianity'),
	url(r'^(?P<poll_id>\d+)/result_islam/$', views.result_islam, name='result_islam'),
	url(r'^(?P<poll_id>\d+)/result_other_religion/$', views.result_other_religion, name='result_other_religion'),
	url(r'^$', IndexView.as_view(), name='index'),
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
	url(r'^(?P<poll_id>\d+)/respondents/$', views.respondents, name='respondents'),
]