# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 14:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('age', models.CharField(choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=10)),
                ('ethnicity', models.CharField(choices=[('Hausa/Fulani', 'Hausa/Fulani'), ('Igbo', 'Igbo'), ('Yoruba', 'Yoruba'), ('Minority-South South', 'Minority-South South'), ('Minority-North Central', 'Minority-North Central'), ('Minority-North East', 'Minority-North East')], max_length=30)),
                ('residence', models.CharField(choices=[('North West', 'North West'), ('North East', 'North East'), ('North Central', 'North Central'), ('South West', 'South West'), ('South East', 'South East'), ('South South', 'South South'), ('Diaspora', 'Diaspora')], max_length=20)),
                ('education', models.CharField(choices=[('Less than secondary school', 'Less than secondary school'), ('Secondary school', 'Secondary school'), ('Graduate', 'Graduate'), ('Post graduate', 'Post graduate')], max_length=50)),
                ('employment', models.CharField(choices=[('Currently unemployed', 'Currently unemployed'), ('Employed full time', 'Employed full time'), ('Employed part time', 'Employed part time'), ('Self employed', 'Self employed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=30)),
                ('income', models.CharField(choices=[('Less than 18,000', 'Less than 18,000'), ('18,000 - 50,000', '18,000 - 50,000'), ('51,000 - 100,000', '51,000 - 100,000'), ('101,000 - 200,000', '101,000 - 200,000'), ('201,000 - 500,000', '201,000 - 500,000'), ('500,000+', '500,000+')], max_length=30)),
                ('marital_status', models.CharField(choices=[('Single-never married', 'Single-never married'), ('Divorced or Separated', 'Divorced or Separated'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=30)),
                ('religion', models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Other', 'Other')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='profile',
            field=models.ManyToManyField(to='polls.Profile'),
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='choice',
            name='profile',
            field=models.ManyToManyField(to='polls.Profile'),
        ),
    ]
