# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employment',
            field=models.CharField(choices=[('Currently unemployed', 'Currently unemployed'), ('Employed full time', 'Employed full time'), ('Employed part time', 'Employed part time'), ('Self employed', 'Self employed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.CharField(choices=[('Less than 18,000', 'Less than 18,000'), ('18,000 - 50,000', '18,000 - 50,000'), ('51,000 - 100,000', '51,000 - 100,000'), ('101,000 - 200,000', '101,000 - 200,000'), ('201,000 - 500,000', '201,000 - 500,000'), ('Greater than 500,000', 'Greater than 500,000')], max_length=30),
        ),
    ]
