# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171130_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='residence',
            field=models.CharField(choices=[('North West', 'North West'), ('North East', 'North East'), ('North Central', 'North Central'), ('South West', 'South West'), ('South East', 'South East'), ('South South', 'South South'), ('Diaspora', 'Diaspora')], max_length=20),
        ),
    ]
