# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171231_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date',
        ),
        migrations.AddField(
            model_name='poll',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
