# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171231_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_published',
        ),
    ]
