# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171130_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.AddField(
            model_name='choice',
            name='profile',
            field=models.ManyToManyField(to='polls.Profile'),
        ),
        migrations.AddField(
            model_name='poll',
            name='profile',
            field=models.ManyToManyField(to='polls.Profile'),
        ),
    ]
