# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171211_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apartment',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65+', '65+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('Less than secondary school', 'Less than secondary school'), ('Secondary school', 'Secondary school'), ('Graduate', 'Graduate'), ('Post graduate', 'Post graduate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.CharField(choices=[('Less than 18,000', 'Less than 18,000'), ('18,000 - 50,000', '18,000 - 50,000'), ('51,000 - 100,000', '51,000 - 100,000'), ('101,000 - 200,000', '101,000 - 200,000'), ('201,000 - 500,000', '201,000 - 500,000'), ('500,000+', '500,000+')], max_length=30),
        ),
    ]
