# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171219_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='created',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated',
        ),
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
    ]
